'use client';

import { Star, Heart, Share2 } from 'lucide-react';
import { motion } from 'framer-motion';

interface Design {
  id: string;
  name: string;
  image: string;
  price: number;
  rating: number;
  sales: number;
  category: string;
}

interface SampleDesignsProps {
  designs: Design[];
}

export default function SampleDesigns({ designs }: SampleDesignsProps) {
  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(price);
  };

  return (
    <div className="px-4 py-8 sm:py-12 lg:py-16 sm:px-6 lg:px-8 bg-champagne/5">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-6 sm:mb-12">
          <h2 className="text-xl sm:text-2xl lg:text-3xl xl:text-4xl font-display font-light text-obsidian-black mb-3 sm:mb-4">
            Sample Generated Designs
          </h2>
          <p className="text-sm sm:text-base lg:text-lg text-graphite max-w-2xl mx-auto">
            See examples of designs generated by our AI from user uploads
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 lg:gap-6">
          {designs.map((design, index) => (
            <motion.div
              key={design.id}
              className="bg-pearl-white rounded-xl sm:rounded-2xl overflow-hidden shadow-luxury-sm hover:shadow-luxury-lg transition-all duration-300 group"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
            >
              <div className="aspect-square bg-champagne/10 overflow-hidden relative">
                <img
                  src={design.image}
                  alt={design.name}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
                <div className="absolute top-2 right-2 sm:top-3 sm:right-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <div className="flex flex-col space-y-1 sm:space-y-2">
                    <button className="p-1.5 sm:p-2 bg-pearl-white/90 backdrop-blur-sm text-graphite rounded-full hover:bg-royal-gold hover:text-obsidian-black transition-all duration-300">
                      <Heart size={12} className="sm:w-4 sm:h-4" />
                    </button>
                    <button className="p-1.5 sm:p-2 bg-pearl-white/90 backdrop-blur-sm text-graphite rounded-full hover:bg-royal-gold hover:text-obsidian-black transition-all duration-300">
                      <Share2 size={12} className="sm:w-4 sm:h-4" />
                    </button>
                  </div>
                </div>
              </div>
              <div className="p-3 sm:p-4">
                <h3 className="text-sm sm:text-base font-semibold text-obsidian-black mb-1 sm:mb-2 line-clamp-1">{design.name}</h3>
                <div className="flex items-center justify-between mb-1 sm:mb-2">
                  <span className="text-royal-gold font-semibold text-sm sm:text-base">{formatPrice(design.price)}</span>
                  <div className="flex items-center space-x-1">
                    <Star size={12} className="sm:w-3.5 sm:h-3.5 text-royal-gold fill-current" />
                    <span className="text-xs sm:text-sm text-graphite">{design.rating}</span>
                  </div>
                </div>
                <div className="flex items-center justify-between text-xs sm:text-sm text-graphite">
                  <span>{design.sales} sales</span>
                  <span className="px-1.5 sm:px-2 py-0.5 sm:py-1 bg-champagne/20 rounded-full text-xs">{design.category}</span>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
